Added `ArcStr::repeat` and `ArcStr::try_repeat`
thomcc/arcstr pull request #50
Opened 2022-11-03 17:03 UTC by Kixiron

Adds the  `ArcStr::repeat` and `ArcStr::try_repeat` functions which are morally equivalent to [`String::repeat`](https://doc.rust-lang.org/std/string/struct.String.html#method.repeat), allows users to avoid an intermediate `String` allocation in some circumstances

2022-11-04 00:04 UTC, thomcc requested changes
The API seems good, and the uninitialized try_allocate looks useful. I would like less duplication if possible, and ideally more tests.

I suppose the linter errors don't seem to be your fault, so I've some necessary blood sacrifices to try and appease clippy in https://github.com/thomcc/arcstr/pull/51 (please rebase).

2022-11-04 00:48 UTC, Kixiron commented on src/arc_str.rs
> +    fn try_allocate_uninit(capacity: usize) -> Result<NonNull<Self>, Option<Layout>> {
There's not, I just didn't do it in the initial pass since I wasn't sure what the policy on changing old code was

2022-11-04 05:47 UTC, thomcc commented
I don't remember what the deal with that error is but I think you need to put the test in the integration test folder.

2022-11-12 05:37 UTC, thomcc approved these changes
LGTM

2022-11-12 05:38 UTC, merged

2022-11-12 06:37 UTC, thomcc commented
in 1.1.5